services:
  backend:
    build:
      context: ./backend
    container_name: agentic-iam-backend
    restart: unless-stopped
    networks:
      - web

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: agentic-iam-frontend
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - web

networks:
  web:
    external: true
